################################################################################################################
#  Endereço do repositório de atualizações do PjeOffice Pro. Configure com 'disabled' (sem aspas) para
#  desabilitar os updates automáticos

update.url=https://pje-office.pje.jus.br/pro/


################################################################################################################
#  Endereço completo da página que mantém a documentação da solução (acessível pelo menu Ajuda)
#  Se não informado, será considerado como endereço a pesquisa google:  https://www.google.com/search?q=pjeoffice-pro

help.url = https://pjeoffice.trf3.jus.br/pjeoffice-pro/docs/index.html


################################################################################################################
#  Arquitetura do instalador. Por favor NÃO edite esta linha se você não souber realmente o que está fazendo

update.architecture=linux.x64.u


################################################################################################################
#  O cabeçalho HTTP "User-Agent" é um cabeçalho de solicitação que fornece informações sobre o cliente (por exemplo, 
#  navegador da web, aplicativo) que faz a solicitação ao servidor. O cabeçalho User-Agent geralmente inclui detalhes 
#  como o nome e a versão do cliente, o sistema operacional em que está sendo executado e qualquer informação 
#  adicional que o cliente queira compartilhar com o servidor.
#
#  Essas informações podem ser úteis para o servidor entender o tipo de cliente que está fazendo a solicitação e 
#  fornecer conteúdo ou respostas apropriados. Por exemplo, um servidor pode usar o cabeçalho User-Agent para 
#  determinar se o cliente é um dispositivo móvel e fornecer uma versão otimizada para dispositivos móveis do site 
#  em resposta
#
#  Nota: O valor padrão deste parâmetro DEVERIA ser 'PJeOffice Pro' (sem aspas), MAS algumas soluções de segurança
#  ex. Akamai, por alguma razão bloqueia requisições com este userAgent. Para manutenção da compatibilidade
#  anterior, o userAgent 'Apache-HttpClient/4.5.6 (Java/1.8.0_301)' (sem aspas) foi definido como padrão por se tratar 
#  do userAgent utilizado pela versão anterior do assinador do CNJ (vanilla).
#  string compatibility: Apache-HttpClient/4.5.6 (Java/1.8.0_301)
#  string specific: PJeOffice Pro

http.client.userAgent = Apache-HttpClient/4.5.6 (Java/1.8.0_301) 


################################################################################################################
#  O maxTotal é um parâmetro que especifica o número máximo de conexões HTTP que podem ser abertas a qualquer 
#  momento pelo cliente.
#
#  O parâmetro maxTotal limita o número total de conexões em todas as rotas (ou seja, para todos os hosts e portas). 
#  Se o cliente tentar abrir mais conexões do que o maxTotal especificado, ele será bloqueado e aguardará uma 
#  conexão ser liberada ou fechada antes de abrir uma nova.
#
#  Por exemplo, se o parâmetro maxTotal for definido como 30, então um cliente pode ter até 30 conexões HTTP abertas 
#  a qualquer momento. Se o cliente tentar abrir uma nova conexão quando o número máximo de conexões já tiver sido 
#  alcançado, ele aguardará a liberação ou o fechamento de uma conexão existente antes de abrir a nova.
#
#  Definir um valor de maxTotal muito baixo pode resultar em timeout de conexão e tempos de resposta lentos 
#  para o cliente, especialmente em ambientes de alto tráfego. Por outro lado, definir um valor de maxTotal muito 
#  alto pode levar à exaustão de recursos na máquina do cliente, pois cada conexão requer recursos de memória e 
#  processamento. O valor ideal de maxTotal dependerá do caso de uso específico e da configuração do sistema.
#
#  Se não configurado, será considerado o valor 600

http.client.connections.maxTotal = 600


################################################################################################################
#  O maxPerRoute é um parâmetro que especifica o número máximo de conexões HTTP que podem ser abertas para uma rota 
#  específica (ou seja, para um host e porta específicos).
#
#  O parâmetro maxPerRoute limita o número de conexões que podem ser abertas para cada rota individualmente. Se o 
#  cliente tentar abrir mais conexões para uma rota do que o maxPerRoute especificado, ele será bloqueado e 
#  aguardará uma conexão ser liberada ou fechada antes de abrir uma nova.
#
#  Vale ressaltar que o parâmetro maxPerRoute é independente do parâmetro maxTotal, que limita o número total de 
#  conexões em todas as rotas. Definir um valor de maxPerRoute muito baixo pode resultar em timeout de conexão 
#  e tempos de resposta lentos para o cliente, especialmente em ambientes de alto tráfego. Por outro lado, definir
#  um valor de maxPerRoute muito alto pode levar à exaustão de recursos na máquina do cliente. O valor ideal de 
#  maxPerRoute dependerá do caso de uso específico e da configuração do sistema.
#
#  ATENÇÃO: Para os fins da plataforma Pje, o assinador NÃO abrirá maxPerRoute conexões simultâneas absolutamente.
#  O total de requisições abertas estará limitada à demanda de conexões que ->o NAVEGADOR<- fará ao assinador e
#  neste contexto este valor é um limite superior por rota demandada ->PELO NAVEGADOR. Navegadores baseados no 
#  motor Chromium costumam usar o valor 6 como máximo por rota. Mozila Firefox usam o valor 6 com tolerância de 
#  3 (portanto até 9). Um valor consideravelmente maior neste parâmetro fará com que o assinador dê preferência 
#  a conexões novas em detrimento das antigas naqueles cenários de "estresse" que comumente ocorrem em assinaturas
#  em lote.
#
#  Se não configurado, será considerado o valor 600.

http.client.connections.maxPerRoute = 600


################################################################################################################
#  O parâmetro connectTimeout é usado para definir o tempo máximo que o cliente irá esperar para que o processo de
#  handshake seja concluído e a conexão estabelecida.
#
#  Vale ressaltar que o connectTimeout só se aplica ao tempo gasto para estabelecer a conexão inicial com o servidor.
#  Uma vez estabelecida a conexão, o cliente pode usá-la pelo tempo que precisar, sujeito a outras configurações
#  de timeout, como o responseTimeout e o keep-alive timeout.
#
#  Quando o cliente inicia uma conexão com o servidor, ele envia uma solicitação ao servidor para iniciar o processo
#  de handshake. O connectTimeout começa a contar a partir do momento em que o cliente envia a solicitação para o
#  servidor. Uma vez que a solicitação tenha sido enviada, o cliente irá aguardar a resposta do servidor e concluir
#  o processo de handshake pelo período de tempo especificado. Se o servidor não responder dentro do período de tempo
#  de timeout, o cliente receberá uma exceção de ConnectTimeoutException.
#
#  Vale ressaltar que o connectTimeout se aplica a todo o processo de handshake, não apenas à tentativa inicial de
#  conexão. Se o processo de handshake envolver várias etapas, como a negociação de chaves de criptografia, cada
#  etapa estará sujeita ao valor do connectTimeout.
#    
#  Unidade de medida: segundos. Se não configurado, será considerado o valor 15

http.client.connectTimeout = 15


################################################################################################################
#  O parâmetro responseTimeout é usado para determinar o tempo máximo que um cliente irá esperar por uma resposta 
#  após enviar uma requisição para o servidor.
#
#  O responseTimeout começa a contar a partir do momento em que o cliente envia a requisição para o servidor. Uma 
#  vez que a requisição foi enviada, o cliente irá esperar pela resposta pelo período de tempo especificado. Se o 
#  servidor não responder dentro do período de tempo limite, o cliente receberá uma exceção SocketTimeoutException.
#
#  Vale ressaltar que o responseTimeout se aplica apenas ao tempo que um cliente passa aguardando uma resposta do 
#  servidor. Depois que a resposta é recebida, o cliente pode usá-la pelo tempo que precisar, sujeito a outras 
#  configurações de timeout, como o keep-alive timeout.
#
#  Quando a resposta HTTP é enviada em vários fragmentos (também conhecido como "chunked encoding"), o parâmetro 
#  responseTimeout é usado para definir o tempo máximo que o cliente irá esperar por cada fragmento.
#
#  Em outras palavras, o responseTimeout é aplicado a cada fragmento individual da resposta, em vez de ser aplicado 
#  à resposta como um todo. O cliente irá esperar por cada fragmento chegar pelo período de tempo especificado e, 
#  se um fragmento não for recebido dentro desse tempo, o cliente considerará que a conexão expirou e irá fechá-la.
#
#  Vale ressaltar que o parâmetro responseTimeout pode ser configurado com um valor relativamente grande para 
#  permitir conexões de rede lentas ou intermitentes, ao mesmo tempo que garante que o cliente irá eventualmente 
#  expirar e fechar a conexão se a resposta estiver demorando muito para chegar. No entanto, configurar o valor de 
#  responseTimeout muito alto também pode resultar em tempos de resposta mais lentos para o cliente, já que o 
#  cliente irá esperar por cada fragmento chegar antes de processá-lo.

#  Unidade de medida: segundos. Se não configurado, será considerado o valor 60

http.client.responseTimeout = 60


################################################################################################################
#  O parâmetro connectionRequestTimeout é usado para determinar o tempo máximo que um cliente esperará para obter
#  uma conexão do pool de conexões.
#
#  O connectionRequestTimeout começa a contar a partir do momento em que o cliente solicita uma conexão do pool 
#  de conexões usando o método HttpClient.execute(). O cliente esperará por uma conexão pelo período de tempo 
#  especificado. Se uma conexão estiver disponível no pool, ela será retornada imediatamente ao cliente. Se nenhuma 
#  conexão estiver disponível dentro do período de tempo limite, o cliente receberá uma exceção 
#  ConnectionPoolTimeoutException.
#
#  É importante notar que o connectionRequestTimeout se aplica apenas ao tempo que um cliente gasta esperando por 
#  uma conexão no pool. Uma vez obtida uma conexão, o cliente pode usá-la pelo tempo que precisar, sujeito às outras 
#  configurações de timeout, como o timeout de manutenção de conexão (keep-alive timeout).
    
#  Unidade de medida: segundos. Se não configurado, será considerado o valor 66

http.client.connectionRequestTimeout = 66


################################################################################################################
#  O parâmetro connectionKeepAliveTimeout é usado para determinar o tempo máximo que uma conexão pode ser mantida
#  aberta (ou seja, mantida viva) no pool de conexões sem ser usada.
#
#  O connectionKeepAliveTimeout começa a contar a partir do momento em que uma conexão se torna ociosa no
#  pool de conexões. Uma conexão ociosa é uma conexão que não está sendo usada atualmente para enviar ou
#  receber dados.
#
#  Quando uma conexão se torna ociosa, o temporizador connectionKeepAliveTimeout começa. Se o tempo desde
#  que a conexão se tornou ociosa exceder o valor especificado para connectionKeepAliveTimeout, a conexão é
#  considerada obsoleta e é fechada pelo gerenciador de conexões.
#
#  Vale ressaltar que o connectionKeepAliveTimeout se aplica apenas às conexões que estão ociosas no pool
#  de conexões. Quando uma conexão está sendo usada para uma solicitação ou resposta, o tempo de keep-alive
#  é determinado pela ConnectionKeepAliveStrategy, e não pelo parâmetro connectionKeepAliveTimeout.

#  Unidade de medida: segundos. Se não configurado, será considerado o valor 5

http.client.connectionKeepAliveTimeout = 5


################################################################################################################
#  O parâmetro evictIdleConnectionTimeout determina o tempo máximo que uma conexão pode ficar ociosa na pool 
#  antes de ser considerada elegível para a remoção.
#
#  O evictIdleConnectionTimeout começa a contar a partir do momento em que uma conexão é devolvida para a pool 
#  depois de ter sido usada. Quando uma conexão é devolvida à pool, seu tempo ocioso é redefinido para zero. 
#  Enquanto a conexão permanecer na pool e não for usada, seu tempo ocioso começará a acumular novamente. Uma vez 
#  que o tempo ocioso de uma conexão exceder o valor de evictIdleConnectionTimeout, ela se torna elegível para a 
#  remoção e será fechada pelo método evictIdleConnections.
#
#  É importante notar que há o método evictIdleConnections que geralmente é chamado periodicamente por uma thread de 
#  segundo plano, e a remoção real das conexões ociosas pode não acontecer imediatamente quando o tempo limite é 
#  atingido. O processo de remoção pode ser adiado dependendo da implementação e configuração específicas da 
#  pool de conexões.

#  Unidade de medida: segundos. Se não configurado, será considerado o valor 5

http.client.evictIdleConnectionTimeout = 5


################################################################################################################
#  O parâmetro validateAfterInactivityTimeout é usado para determinar o período máximo de inatividade de uma 
#  conexão ociosa antes que ela seja validada como ainda estando disponível para reutilização.
#
#  O validateAfterInactivityTimeout começa a contar a partir do momento em que uma conexão é devolvida ao pool após 
#  ter sido usada. Quando uma conexão é devolvida ao pool, seu horário de última utilização é registrado. Se a 
#  conexão permanecer ociosa no pool por um período de tempo igual ou superior ao valor do validateAfterInactivityTimeout, 
#  a conexão será validada antes de ser entregue para reutilização. Se a conexão não passar na validação, ela será 
#  fechada e removida do pool.
#
#  Vale ressaltar que o parâmetro validateAfterInactivityTimeout não é usado para fechar ativamente conexões ociosas 
#  como o parâmetro evictIdleConnectionTimeout. Em vez disso, é usado para garantir que as conexões que ficaram 
#  ociosas por um longo período de tempo ainda sejam válidas e possam ser reutilizadas com segurança. Validando 
#  periodicamente as conexões, o pool de conexões pode evitar entregar conexões que ficaram obsoletas ou foram fechadas 
#  pelo servidor.
    
#  Unidade de medida: segundos. Se não configurado, será considerado o valor 2

http.client.validateAfterInactivityTimeout = 2

