import re
from pathlib import Path

# Path to the migration file
migration_dir = Path("alembic/versions")
migration_file = next(migration_dir.glob("*_initial_schema.py"))

with open(migration_file, "r") as f:
    content = f.read()

# Split the content into three parts: before upgrade, upgrade, downgrade
parts = re.split(r'def upgrade\(\) -> None:', content)
header = parts[0]
rest = parts[1]

upgrade_downgrade = re.split(r'def downgrade\(\) -> None:', rest)
upgrade_content = upgrade_downgrade[0]
downgrade_content = downgrade_downgrade = upgrade_downgrade[1]

# In upgrade_content, extract the table creation blocks
# Each table creation block starts with op.create_table( and ends with ) followed by some op.create_index
# We can find all op.create_table commands
import ast

def extract_tables(code_str):
    tables = {}
    
    # We'll use simple regex to extract op.create_table blocks and their associated op.create_index blocks
    # A cleaner way is just to move tenants, tags, users to the top of upgrade manually.
    pass

# Actually, an easier regex replacement:
# The order is currently messed up. We just need to move tenants, users, tags to the top of upgrade.

# Let's extract the full op.create_table/index blocks for tenants, users, tags
def extract_block(table_name, text):
    # Find op.create_table('table_name', ... ) and matching op.create_index block
    pattern = r"    op\.create_table\('" + table_name + r"',.*?(?=    op\.create_table\('|    # ### end Alembic commands|    op\.execute|\Z)"
    match = re.search(pattern, text, re.DOTALL)
    if match:
        return match.group(0)
    return ""

tenants_block = extract_block("tenants", upgrade_content)
users_block = extract_block("users", upgrade_content)
tags_block = extract_block("tags", upgrade_content)

# Remove them from upgrade_content
upgrade_content = upgrade_content.replace(tenants_block, "")
upgrade_content = upgrade_content.replace(users_block, "")
upgrade_content = upgrade_content.replace(tags_block, "")

# Insert them at the beginning of upgrade_content (after the first line: '    # ### commands auto generated by Alembic - please adjust! ###\n')
insert_pos = upgrade_content.find("###\n") + 4
new_upgrade = upgrade_content[:insert_pos] + tenants_block + users_block + tags_block + upgrade_content[insert_pos:]

# Now we need to fix the circular dependency between leads and clients.
# leads has: sa.ForeignKeyConstraint(['converted_to_client_id'], ['clients.id'], ondelete='SET NULL'),
# We will remove this from leads create_table, and add it via op.create_foreign_key at the end of upgrade.

leads_fk = "    sa.ForeignKeyConstraint(['converted_to_client_id'], ['clients.id'], ondelete='SET NULL'),\n"
clients_fk = "    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),\n"
new_upgrade = new_upgrade.replace(leads_fk, "")
new_upgrade = new_upgrade.replace(clients_fk, "")

# Find the end of Alembic commands to insert the FK
end_alembic = "    # ### end Alembic commands ###"
fk_addition = "    op.create_foreign_key('fk_leads_converted_to_client', 'leads', 'clients', ['converted_to_client_id'], ['id'], ondelete='SET NULL')\n"
fk_addition2 = "    op.create_foreign_key('fk_clients_lead_id', 'clients', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')\n"
new_upgrade = new_upgrade.replace(end_alembic, fk_addition + fk_addition2 + end_alembic)

# Now write it out
new_content = header + "def upgrade() -> None:" + new_upgrade + "def downgrade() -> None:" + downgrade_content

with open(migration_file, "w") as f:
    f.write(new_content)

print(f"Fixed migration file: {migration_file.name}")
