"""Add email verification to user

Revision ID: 57c5d51be3d2
Revises: a2b3c4d5e6f7
Create Date: 2026-03-01 06:56:01.458276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57c5d51be3d2'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_integrations_tenant_id'), table_name='user_integrations')
    op.drop_index(op.f('ix_user_integrations_user_id'), table_name='user_integrations')
    op.drop_table('user_integrations')
    op.alter_column('leads', 'instagram_username',
               existing_type=sa.VARCHAR(length=100),
               comment='Instagram username for DM leads',
               existing_nullable=True)
    op.alter_column('leads', 'instagram_profile_picture_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Cached Instagram profile picture URL',
               existing_nullable=True)
    op.alter_column('peticao_documentos', 'tipo_documento',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PETICAO_PRINCIPAL', 'PROCURACAO', 'ANEXO', 'COMPROVANTE', name='tipo_documento_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('peticao_documentos', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('UPLOADING', 'UPLOADED', 'ERROR', 'VALIDADO', name='documento_status_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('peticao_eventos', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('RASCUNHO', 'VALIDANDO', 'ASSINANDO', 'PROTOCOLANDO', 'PROTOCOLADA', 'ACEITA', 'REJEITADA', name='peticao_status_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('peticoes', 'tipo_peticao',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PETICAO_INICIAL', 'CONTESTACAO', 'RECURSO_APELACAO', 'AGRAVO_INSTRUMENTO', 'EMBARGOS_DECLARACAO', 'HABEAS_CORPUS', 'MANDADO_SEGURANCA', 'MANIFESTACAO', 'OUTRO', name='tipo_peticao_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('peticoes', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('RASCUNHO', 'VALIDANDO', 'ASSINANDO', 'PROTOCOLANDO', 'PROTOCOLADA', 'ACEITA', 'REJEITADA', name='peticao_status_enum', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_peticoes_certificado_id'), 'peticoes', ['certificado_id'], unique=False)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, comment='Whether user has verified their email'))
    op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True, comment='Token for email verification'))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='User phone number',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL to user avatar image',
               existing_nullable=True)
    op.alter_column('users', 'oab_number',
               existing_type=sa.VARCHAR(length=20),
               comment='OAB registration number (digits only)',
               existing_nullable=True)
    op.alter_column('users', 'oab_state',
               existing_type=sa.VARCHAR(length=2),
               comment='OAB state (2-letter code, e.g. SP, RJ)',
               existing_nullable=True)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.alter_column('users', 'oab_state',
               existing_type=sa.VARCHAR(length=2),
               comment=None,
               existing_comment='OAB state (2-letter code, e.g. SP, RJ)',
               existing_nullable=True)
    op.alter_column('users', 'oab_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='OAB registration number (digits only)',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL to user avatar image',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='User phone number',
               existing_nullable=True)
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_peticoes_certificado_id'), table_name='peticoes')
    op.alter_column('peticoes', 'status',
               existing_type=sa.Enum('RASCUNHO', 'VALIDANDO', 'ASSINANDO', 'PROTOCOLANDO', 'PROTOCOLADA', 'ACEITA', 'REJEITADA', name='peticao_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('peticoes', 'tipo_peticao',
               existing_type=sa.Enum('PETICAO_INICIAL', 'CONTESTACAO', 'RECURSO_APELACAO', 'AGRAVO_INSTRUMENTO', 'EMBARGOS_DECLARACAO', 'HABEAS_CORPUS', 'MANDADO_SEGURANCA', 'MANIFESTACAO', 'OUTRO', name='tipo_peticao_enum', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('peticao_eventos', 'status',
               existing_type=sa.Enum('RASCUNHO', 'VALIDANDO', 'ASSINANDO', 'PROTOCOLANDO', 'PROTOCOLADA', 'ACEITA', 'REJEITADA', name='peticao_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('peticao_documentos', 'status',
               existing_type=sa.Enum('UPLOADING', 'UPLOADED', 'ERROR', 'VALIDADO', name='documento_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('peticao_documentos', 'tipo_documento',
               existing_type=sa.Enum('PETICAO_PRINCIPAL', 'PROCURACAO', 'ANEXO', 'COMPROVANTE', name='tipo_documento_enum', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('leads', 'instagram_profile_picture_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Cached Instagram profile picture URL',
               existing_nullable=True)
    op.alter_column('leads', 'instagram_username',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Instagram username for DM leads',
               existing_nullable=True)
    op.create_table('user_integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('access_token_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('external_user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('external_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('external_profile_picture_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('user_integrations_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_integrations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_integrations_pkey')),
    sa.UniqueConstraint('tenant_id', 'user_id', 'integration_type', name=op.f('uq_user_integrations_tenant_user_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_integrations_tenant_id'), 'user_integrations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
