"""add_worker_scheduler_and_agent_logs

Revision ID: a084d486203a
Revises: a1b2c3d4e5f6
Create Date: 2026-02-28 10:54:20.186702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a084d486203a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_execution_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant that triggered the execution',
               existing_nullable=True)
    op.alter_column('agent_execution_logs', 'agent_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Agent name: triagem, investigador, redator, maestro',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Execution status: running, success, error',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'provider_used',
               existing_type=sa.VARCHAR(length=50),
               comment='LLM provider: openai, anthropic, google',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'model_used',
               existing_type=sa.VARCHAR(length=100),
               comment='Model identifier used',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'duration_ms',
               existing_type=sa.INTEGER(),
               comment='Execution duration in milliseconds',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment='Error message if execution failed',
               existing_nullable=True)
    op.alter_column('agent_execution_logs', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional execution metadata',
               existing_nullable=True)
    op.alter_column('worker_schedules', 'task_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique task identifier: datajud_poller, morning_briefing, etc',
               existing_nullable=False)
    op.alter_column('worker_schedules', 'cron_expression',
               existing_type=sa.VARCHAR(length=100),
               comment="Cron expression: '0 */6 * * *'",
               existing_nullable=False)
    op.alter_column('worker_schedules', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Task-specific configuration parameters',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('worker_schedules', 'description',
               existing_type=sa.TEXT(),
               server_default=None,
               comment='Human-readable description of the task',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_schedules', 'description',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               comment=None,
               existing_comment='Human-readable description of the task',
               existing_nullable=False)
    op.alter_column('worker_schedules', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Task-specific configuration parameters',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('worker_schedules', 'cron_expression',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Cron expression: '0 */6 * * *'",
               existing_nullable=False)
    op.alter_column('worker_schedules', 'task_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Unique task identifier: datajud_poller, morning_briefing, etc',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional execution metadata',
               existing_nullable=True)
    op.alter_column('agent_execution_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if execution failed',
               existing_nullable=True)
    op.alter_column('agent_execution_logs', 'duration_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Execution duration in milliseconds',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'model_used',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Model identifier used',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'provider_used',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='LLM provider: openai, anthropic, google',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Execution status: running, success, error',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'agent_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Agent name: triagem, investigador, redator, maestro',
               existing_nullable=False)
    op.alter_column('agent_execution_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tenant that triggered the execution',
               existing_nullable=True)
    # ### end Alembic commands ###
